### ISSUE TITLE
Query: Extension status

### ISSUE THREAD

**Issue by Gitoffthelawn** [fwenzel/deblankify#3]
What is the status of this excellent extension?

It looks like it has been removed from AMO.

**Comment by fwenzel** [comment]
How on earth did I not see this?

Sorry for the insanely late answer: This extension is not needed, you can simply flip a setting in Firefox. (Though I could just use this extension to expose that setting, I suppose).

Go to `about:config` and edit this setting: `browser.link.open_newwindow`. Default value is 3, which means open `_blank` links in a new tab. Set that to 1 to open in current tab.

There's an explanation page for these settings on [mozillazine](http://kb.mozillazine.org/About:config_entries#Browser.).

Hope this helps!!!
